package lexer

type TokenType int

const (
	EOF TokenType = iota
	
	STRING
	NUMBER
	IDENTIFIER

	// SINGLE-CHARS TOKEN ---
	LEFT_BRACE
	RIGHT_BRACE
	LEFT_PARENTHESIS
	RIGHT_PARENTHESIS
	LEFT_BRACKET
	RIGHT_BRACKET
	COMMA
	SEMICOLON
	COLON

	ASSIGNMENT
	PLUS
	MINUS
	SLASH
	STAR
	MODULO
	DOT

	// LOGICAL OPERATORS ---
	NOT
	OR
	AND
	
	// COMPARISON OPERATORS ---
	LESS
	LESS_EQUAL
	GREATER
	GREATER_EQUAL
	EQUAL
	NOT_EQUAL

	// TWO-CHARS TOKEN ---
	PLUS_PLUS
	PLUS_EQUALS
	MINUS_MINUS
	MINUS_EQUALS
	STAR_EQUALS
	SLASH_EQUALS
	MODULO_EQUALS

	// RESERVED KEYWORDS ---
	VARIABLE
	CONSTANT
)

var RESERVED_KEYWORDS = map[string]TokenType{
	"var": VARIABLE,
	"const": CONSTANT,
}

var TokenTypeString = map[TokenType]string{
	EOF: "EOF",
	STRING: "STRING",
	NUMBER: "NUMBER",
	IDENTIFIER: "IDENTIFIER",

	LEFT_BRACE: "LEFT_BRACE",
	RIGHT_BRACE: "RIGHT_BRACE",
	LEFT_PARENTHESIS: "LEFT_PARENTHESIS",
	RIGHT_PARENTHESIS: "RIGHT_PARENTHESIS",
	LEFT_BRACKET: "LEFT_BRACKET",
	RIGHT_BRACKET: "RIGHT_BRACKET",
	COMMA: "COMMA",
	SEMICOLON: "SEMICOLON",
	COLON: "COLON",

	ASSIGNMENT: "ASSIGNMENT",
	PLUS: "PLUS",
	MINUS: "MINUS",
	SLASH: "SLASH",
	STAR: "STAR",
	MODULO: "MODULO",
	DOT: "DOT",

	NOT: "NOT",
	AND: "AND",
	OR: "OR",

	LESS: "LESS",
	LESS_EQUAL: "LESS_EQUAL",
	GREATER: "GREATER",
	GREATER_EQUAL: "GREATER_EQUAL",
	EQUAL: "EQUAL",
	NOT_EQUAL: "NOT_EQUAL",

	PLUS_PLUS: "PLUS_PLUS",
	PLUS_EQUALS: "PLUS_EQUALS",
	MINUS_MINUS: "MINUS_MINUS",
	MINUS_EQUALS: "MINUS_EQUALS",
	STAR_EQUALS: "STAR_EQUALS",
	SLASH_EQUALS: "SLASH_EQUALS",
	MODULO_EQUALS: "MODULO_EQUALS",

	VARIABLE: "VARIABLE",
	CONSTANT: "CONSTANT",
}
